# --- !Ups

ALTER TABLE t_category DROP CONSTRAINT uq_T_TASK_CATEGORY_1;
ALTER TABLE t_place DROP CONSTRAINT uq_T_PLACE_1;
ALTER TABLE t_tag DROP CONSTRAINT uq_T_TAG_1;

# --- !Downs

ALTER TABLE t_category ADD CONSTRAINT uq_T_TASK_CATEGORY_1 UNIQUE(idUser, name);
ALTER TABLE t_place ADD CONSTRAINT uq_T_PLACE_1 UNIQUE(idUser, name);
ALTER TABLE t_tag ADD CONSTRAINT uq_T_TAG_1 UNIQUE(idUser, name);