# --- !Ups

RENAME TABLE T_TASK_CATEGORY TO T_CATEGORY;

CREATE TABLE T_CONFIGURATION (
  confkey                   varchar(32) not null,
  value                     varchar(64),
  CONSTRAINT pk_T_CONFIGURATION PRIMARY KEY (confkey))
;

ALTER TABLE T_PLACE ADD uuid VARCHAR(47) DEFAULT null;
ALTER TABLE T_TAG ADD uuid VARCHAR(47) DEFAULT null;
ALTER TABLE T_CATEGORY ADD uuid VARCHAR(47) DEFAULT null;
ALTER TABLE T_TASK ADD uuid VARCHAR(47) DEFAULT null;

# --- !Downs

ALTER TABLE T_PLACE DROP uuid;
ALTER TABLE T_TAG DROP uuid;
ALTER TABLE T_CATEGORY DROP uuid;
ALTER TABLE T_TASK DROP uuid;

DROP TABLE T_CONFIGURATION;

RENAME TABLE T_CATEGORY TO T_TASK_CATEGORY;