# --- !Ups

ALTER TABLE T_TASK_CATEGORY RENAME TO T_CATEGORY;

ALTER SEQUENCE T_TASK_CATEGORY_seq RENAME TO T_CATEGORY_seq;

CREATE TABLE T_CONFIGURATION (
  confkey                   varchar(32) not null,
  value                     varchar(64),
  CONSTRAINT pk_T_CONFIGURATION PRIMARY KEY (confkey))
;

ALTER TABLE T_PLACE ADD COLUMN uuid VARCHAR(47) DEFAULT null;
ALTER TABLE T_TAG ADD COLUMN uuid VARCHAR(47) DEFAULT null;
ALTER TABLE T_CATEGORY ADD COLUMN uuid VARCHAR(47) DEFAULT null;
ALTER TABLE T_TASK ADD COLUMN uuid VARCHAR(47) DEFAULT null;

# --- !Downs

ALTER TABLE T_PLACE DROP COLUMN uuid;
ALTER TABLE T_TAG DROP COLUMN uuid;
ALTER TABLE T_CATEGORY DROP COLUMN uuid;
ALTER TABLE T_TASK DROP COLUMN uuid;

DROP TABLE IF EXISTS T_CONFIGURATION cascade;

ALTER SEQUENCE T_CATEGORY_seq RENAME TO T_TASK_CATEGORY_seq;

ALTER TABLE T_CATEGORY RENAME TO T_TASK_CATEGORY;